### ISSUE TITLE
DNS label is too short (Acme::Client::Error::Malformed)

### ISSUE THREAD

**Issue by KMarshland** [sorah/acmesmith#9]
When I try to authorize a domain, I get the following error:
```
acmesmith authorize domain.name. -c ./config/acmesmith/production.yml

/Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acme-client-0.4.0/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': DNS label is too short (Acme::Client::Error::Malformed)
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acme-client-0.4.0/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acme-client-0.4.0/lib/acme/client/faraday_middleware.rb:18:in `block in call'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acme-client-0.4.0/lib/acme/client/faraday_middleware.rb:18:in `call'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acme-client-0.4.0/lib/acme/client.rb:57:in `authorize'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acmesmith-0.4.1/lib/acmesmith/command.rb:27:in `authorize'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/gems/acmesmith-0.4.1/bin/acmesmith:4:in `<top (required)>'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/bin/acmesmith:23:in `load'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/bin/acmesmith:23:in `<main>'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kaimarshland/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

My config looks like this:
```
endpoint: https://acme-v01.api.letsencrypt.org/
storage:
  type: s3
  region: 'us-west-1'
  bucket: 'my-bucket'
  prefix: 'production'

challenge_responders:
  - route53: {}

account_key_passphrase: password
certificate_key_passphrase: secret
```

I have registered using:
`acmesmith register mailto:myemail@gmail.com -c ./config/acmesmith/production.yml`

I am using acmesmith 0.4.1 and acme-client (0.4.0). While the final error is thrown by the acme client, it seems like the cause is from sending an invalid request.

**Comment by sorah** [comment]
Looks like `domain.name.` is invalid FQDN.
